services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: reservsystem
      POSTGRES_USER: usersystem
      POSTGRES_PASSWORD: passreserv
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - app-network

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/reservsystem
      SPRING_DATASOURCE_USERNAME: usersystem
      SPRING_DATASOURCE_PASSWORD: passreserv
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
